student_Data_Management_System/data/urls.py
from django.contrib import admin
from django.urls import path
from data import views

urlpatterns = [
    path('',views.show_Student_Data,name='Show_data'),
    path('add_Data/',views.add_Student_Data,name='Add_data'),
    path('update_Data/<int:id>/',views.edit_Student_Data,name='Update_data'),
    path('view_Single_Data/<int:id>/',views.single_Person_Data,name='Single_data'),
    path('delete_Data/<int:id>/',views.delete_Student_Data,name='Delete_data'),
    path('accounts/register/',views.register,name='Register'),
    path('accounts/login/',views.login,name='Login'),
    path('logout/',views.logout,name='Logout'),
]

student_Data_Management_System/student_Data_Management_System/urls.py
from django.contrib import admin
from django.urls import path, include
from data import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('data.urls')),
    path('register/',views.register,name='Register')
]

student_Data_Management_System/data/models.py
from django.db import models
from django.contrib.auth.models import User

class Student_Data_Model(models.Model):
    name = models.CharField(max_length=50)
    father_name =models.CharField(max_length=60)
    mother_name =models.CharField(max_length=60)
    roll_number = models.IntegerField()
    email = models.EmailField(max_length=254)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    
    
    
# password = Ak@123 Username = Awnish1    

student_Data_Management_System/data/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm,PasswordChangeForm,SetPasswordForm
from django.contrib.auth.models import User
from .models import Student_Data_Model

class registerForm(UserCreationForm):
    # usable_password = None
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'w-full px-5 py-1 text-orange-600 border-2 rounded-md shadow-sm focus:outline-none focus:ring-orange-600 focus:border-orange-600 sm:text-sm','placeholder' : "Enter Password" }),label='Password')
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'w-full px-5 py-1 text-orange-600 border-2 rounded-md shadow-sm focus:outline-none focus:ring-orange-600 focus:border-orange-600 sm:text-sm','placeholder' : "Confirm Password"}),label=' Confirm Password')
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'w-full px-5 py-1 text-orange-600 border-2 rounded-md shadow-sm focus:outline-none focus:ring-orange-600 focus:border-orange-600 sm:text-sm','placeholder' : "Enter Your Username"}),label='UserName')
    email = forms.CharField(widget=forms.EmailInput(attrs={'class':'w-full px-5 py-1 text-orange-600 border-2 rounded-md shadow-sm focus:outline-none focus:ring-orange-600 focus:border-orange-600 sm:text-sm','placeholder' : "Enter Your Email"}),label='Email')
    class Meta:
        model = User
        fields = ['username','email','password1','password2']


class Add_Data_Form(forms.ModelForm):
    class Meta:
        model = Student_Data_Model
        fields = '__all__'
        widgets = {
           'name' : forms.TextInput(attrs={
               'class' : 'w-full px-5 py-1 text-orange-600 border-2 rounded-md shadow-sm focus:outline-none focus:ring-orange-600 focus:border-orange-600 sm:text-sm',
               'placeholder': 'Enter Your Name',
           }),
           'father_name' : forms.TextInput(attrs={
               'class' : 'w-full px-5 py-1 text-orange-600 border-2 rounded-md shadow-sm focus:outline-none focus:ring-orange-600 focus:border-orange-600 sm:text-sm',
               'placeholder': 'Enter Father Name'
           }),
           'mother_name' : forms.TextInput(attrs={
               'class' : 'w-full px-5 py-1 text-orange-600 border-2 rounded-md shadow-sm focus:outline-none focus:ring-orange-600 focus:border-orange-600 sm:text-sm',
               'placeholder': 'Enter Mother Name'
           }),
           'email' : forms.EmailInput(attrs={
               'class' : 'w-full px-5 py-1 text-orange-600 border-2 rounded-md shadow-sm focus:outline-none focus:ring-orange-600 focus:border-orange-600 sm:text-sm',
               'placeholder': 'Enter Your Gmail'
           }),
           'roll_number' : forms.TextInput(attrs={
               'class' : 'w-full px-5 py-1 text-orange-600 border-2 rounded-md shadow-sm focus:outline-none focus:ring-orange-600 focus:border-orange-600 sm:text-sm',
               'placeholder': 'Enter Your RollNo.'
           }),
        }

student_Data_Management_System/data/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import registerForm, Add_Data_Form
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login, authenticate, logout as auth_logout
from django.contrib.auth.decorators import login_required
from .models import Student_Data_Model


# Register Part 
def register(request):
    if request.method == 'POST':
        register_Form = registerForm(request.POST)
        if register_Form.is_valid():
            register_Form.save()
            register_Form = registerForm()
            messages.add_message(request, messages.SUCCESS, "Account Created Successfully!")
            return redirect('Login')
    else:
        register_Form = registerForm()
    return render(request,'registration/register.html',{'r_forms': register_Form})


# Login Part
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            name = form.cleaned_data['username']
            pwd = form.cleaned_data['password']
            user = authenticate(request, username = name, password = pwd) 
            if user is not None:
                auth_login(request,user)
                messages.add_message(request, messages.SUCCESS, "You're logIn Successfully!")
                return redirect('Add_data') 
    else:
        form = AuthenticationForm()
    return render(request,'registration/login.html',{'l_forms':form})

# Logout Part 
def logout(request):
    auth_logout(request)
    return redirect('Show_data')

# View All Data 
def show_Student_Data(request):
    show_Data = Student_Data_Model.objects.all()
    return render(request,'show_Data.html',{'show_Data':show_Data})

# Add Data From UI
@login_required
def add_Student_Data(request):
    if request.method == 'POST':
        form_Data = Add_Data_Form(request.POST)
        if form_Data.is_valid():
            form_Data.save()
            form_Data = Add_Data_Form()
            return redirect('Show_data')
    else:
        form_Data = Add_Data_Form()
    return render(request,'add_Data.html',{'form_Data':form_Data})


# Edit Single person Data
@login_required
def edit_Student_Data(request,id):
    if request.method == 'POST':
        get_Data_Model = Student_Data_Model.objects.get(pk = id)
        edit_forms = Add_Data_Form(request.POST,instance=get_Data_Model)
        if edit_forms.is_valid():
            edit_forms.save()
            return redirect('Show_data')
    else:
        get_Data_Model = Student_Data_Model.objects.get(pk = id)
        edit_forms = Add_Data_Form(instance=get_Data_Model)
    return render(request,'update_Details.html',{'edit_forms':edit_forms})


# Delete Data 
@login_required
def delete_Student_Data(request,id):
    if request.method == 'POST':
        get_Data_Model = Student_Data_Model.objects.get(pk = id)
        get_Data_Model.delete()
        return redirect('Show_data')


# View Single Person Data
@login_required
def single_Person_Data(request,id):
    view_Data = get_object_or_404(Student_Data_Model,pk=id)
    return render(request,'view_Single_Data.html',{'view_Data':view_Data})

student_Data_Management_System/data/templates/add_Data.html
{% extends "layout.html" %}


{% block title %}
    Add And Showing Deatails Of Students
{% endblock title %}


{% block content %}
<h1 class="text-center text-3xl md:text-4xl lg:text-5xl font-bold p-5 text-orange-600">
    Student Data Management System In Django
  </h1>
  <div class="flex justify-center items-center p-4">
    <div class="border-2 border-orange-600 w-full sm:w-4/5 md:w-3/5 lg:w-2/5">
      <h1 class="text-center text-xl md:text-2xl lg:text-3xl font-bold p-4 bg-orange-600 text-white">
        Add Student Details
      </h1>
      <form method="post" class="text-orange-600 p-5">
        {% csrf_token %}
        <div>
          <div class="mb-4">
            <label for="id_name" class="text-lg md:text-xl font-medium text-orange-600 block mb-2">
              First Name:
            </label>
            {{ form_Data.name }}
          </div>
          <div class="mb-4">
            <label for="id_father_name" class="text-lg md:text-xl font-medium text-orange-600 block mb-2">
              Father Name:
            </label>
            {{ form_Data.father_name }}
          </div>
          <div class="mb-4">
            <label for="id_mother_name" class="text-lg md:text-xl font-medium text-orange-600 block mb-2">
              Mother Name:
            </label>
            {{ form_Data.mother_name }}
          </div>
          <div class="mb-4">
            <label for="id_email" class="text-lg md:text-xl font-medium text-orange-600 block mb-2">
              Gmail:
            </label>
            {{ form_Data.email }}
          </div>
          <div class="mb-4">
            <label for="id_roll_number" class="text-lg md:text-xl font-medium text-orange-600 block mb-2">
              Roll No:
            </label>
            {{ form_Data.roll_number }}
          </div>
        </div>
        <div class="flex flex-wrap gap-3 mt-4">
          <button
            class="inline-flex items-center justify-center px-4 py-2 border border-transparent text-sm md:text-base font-medium rounded-md text-white bg-orange-600 hover:bg-orange-700 focus:outline-none focus:ring-2 focus:ring-orange-500"
            type="submit">
            Add
          </button>
          <a
            href="{% url 'Show_data' %}"
            class="inline-flex items-center justify-center px-4 py-2 border border-transparent text-sm md:text-base font-medium rounded-md text-white bg-orange-600 hover:bg-orange-700 focus:outline-none focus:ring-2 focus:ring-orange-500">
            View Data
          </a>
        </div>
      </form>
    </div>
  </div>
  
{% endblock content %}
    
    

student_Data_Management_System/data/templates/show_Data.html
{% extends "layout.html" %}

{% block title %}
    Show All Data Of The Student
{% endblock title %}



{% block content %}
<h1 class="text-center text-3xl md:text-4xl lg:text-5xl font-bold p-5 text-orange-600 mb-3">
  Student Data Management System In Django
</h1>
<div class="flex justify-center items-center mb-4 px-4">
  <div class="border-4 border-orange-600 w-full sm:w-5/6 md:w-4/6">
    <h1 class="text-center text-xl md:text-2xl lg:text-3xl font-bold p-4 text-white bg-orange-600">
      Show All Student Data
    </h1>

    {% if show_Data %}
    <div class="overflow-x-auto">
      <table class="table-auto border-collapse border border-orange-600 w-full text-center text-sm md:text-base">
        <thead>
          <tr class=" border border-orange-600 text-orange-600 text-sm md:text-lg">
            <th class="border border-orange-600 px-3 py-2">Name</th>
            <th class="border border-orange-600 px-3 py-2">Father Name</th>
            <th class="border border-orange-600 px-3 py-2">Mother Name</th>
            <th class="border border-orange-600 px-4 py-2">Roll No.</th>
            <th class="border border-orange-600 px-4 py-2">Gmail</th>
            <th class="border border-orange-600 px-5 py-2">Update | Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for ustd in show_Data %}
          <tr class="text-orange-600">
            <td class="border border-orange-600 py-2 px-1">
              <a href="{% url 'Single_data' ustd.id%}" class="hover:underline">{{ ustd.name }}</a>
            </td>
            <td class="border border-orange-600 py-2">{{ ustd.father_name }}</td>
            <td class="border border-orange-600 py-2">{{ ustd.mother_name }}</td>
            <td class="border border-orange-600 py-2">{{ ustd.roll_number }}</td>
            <td class="border border-orange-600 py-2 px-1">{{ ustd.email }}</td>
            <td class="border border-orange-600 py-2">
              <div class="flex justify-center gap-2">
                <a href="{% url 'Update_data' ustd.id%}">
                  <button type="button" class="px-3 py-2 text-xs md:text-sm font-bold rounded-md text-white bg-orange-600 hover:bg-orange-700 focus:outline-none focus:ring-2">
                    Edit
                  </button>
                </a>
                <form method="post" action="{% url 'Delete_data' ustd.id%}">
                  {% csrf_token %}
                  <button
                    class="px-3 py-2 text-xs md:text-sm font-bold rounded-md text-white bg-orange-600 hover:bg-orange-700 focus:outline-none focus:ring-2"
                    type="submit">
                    Delete
                  </button>
                </form>
              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% else %}
    <h2 class="text-center w-full text-xl md:text-2xl font-bold text-orange-600 p-4">
      No Record Of the Student
    </h2>
    {% endif %}
  </div>
</div>

<div class="flex justify-center">
  <a href="{% url 'Add_data' %}"
    class="px-4 py-2 border border-transparent text-sm md:text-base font-bold rounded-md text-white bg-orange-600 hover:bg-orange-700 focus:outline-none focus:ring-2">
    Add Data
  </a>
</div>
   
{% endblock content %}
    
    

student_Data_Management_System/data/templates/update_Details.html
{% extends "layout.html" %}


{% block title %}
    Update Student Details
{% endblock title %}


{% block content %} 
<h1 class="text-center text-4xl md:text-5xl font-bold p-5 text-orange-600">
    Student Data Management System In Django
  </h1>
  <div class="flex items-center justify-center px-4">
    <div class="py-5 w-full md:w-3/5">
      <h1 class="text-center text-2xl md:text-3xl font-bold p-4 bg-orange-600 text-white">
        Update Student Data
      </h1>
      <form action="" method="POST" class="border-2 border-orange-600 text-orange-600 p-5">
        {% csrf_token %}
        <div class="space-y-4">
          {{edit_forms}}
        </div>
        <div class="pt-4 flex flex-col sm:flex-row items-center sm:justify-between">
          <button
            type="submit"
            class="px-4 py-2 mb-3 sm:mb-0 sm:mr-3 border border-transparent text-sm font-bold rounded-md text-white bg-orange-600 hover:bg-orange-700 focus:outline-none focus:ring-2"
          >
            Update
          </button>
          <a
            href="{% url 'Show_data' %}"
            class="px-4 py-2 border border-transparent text-sm font-bold rounded-md text-white bg-orange-600 hover:bg-orange-700 focus:outline-none focus:ring-2"
          >
            Back to Home
          </a>
        </div>
      </form>
    </div>
  </div>
  
  
{% endblock content %}
    

student_Data_Management_System/data/templates/view_Single_Data.html
{% extends "layout.html" %}


{% block title %}
    View Singe Person data
{% endblock title %}
    


{% block content %}
<h1 class="text-center text-4xl md:text-5xl font-bold p-5 text-orange-600">
    Student Data Management System In Django
  </h1>
  <div class="flex items-center justify-center px-4">
    <div class="py-5 w-full md:w-3/5">
      <h1 class="text-center text-2xl md:text-3xl font-bold p-4 bg-orange-600 text-white">
        Single Person Data
      </h1>
      <div class="border-2 py-3 px-5 border-orange-600 mb-5">
        <h3 class="text-lg md:text-2xl text-orange-600 mb-3">
          <span class="font-bold">Name:</span>&nbsp;{{view_Data.name}}
        </h3>
        <h3 class="text-lg md:text-2xl text-orange-600 mb-3">
          <span class="font-bold">Father Name:</span>&nbsp;{{view_Data.father_name}}
        </h3>
        <h3 class="text-lg md:text-2xl text-orange-600 mb-3">
          <span class="font-bold">Mother Name:</span>&nbsp;{{view_Data.mother_name}}
        </h3>
        <h3 class="text-lg md:text-2xl text-orange-600 mb-3">
          <span class="font-bold">Roll No:</span>&nbsp;{{view_Data.roll_number}}
        </h3>
        <h3 class="text-lg md:text-2xl text-orange-600 mb-3">
          <span class="font-bold">Email:</span>&nbsp;{{view_Data.email}}
        </h3>
      </div>
      <div class="pt-2 flex flex-col sm:flex-row items-center sm:justify-between">
        <a
          href="{% url 'Show_data' %}"
          class="mb-3 sm:mb-0 sm:mr-3 px-4 py-2 border border-transparent text-sm font-bold rounded-md text-white bg-orange-600 hover:bg-orange-700 focus:outline-none focus:ring-2"
        >
          Back to Home
        </a>
        <a
          href="{% url 'Show_data' %}"
          class="px-4 py-2 border border-transparent text-sm font-bold rounded-md text-white bg-orange-600 hover:bg-orange-700 focus:outline-none focus:ring-2"
        >
          All Data
        </a>
      </div>
    </div>
  </div>
  
{% endblock content %}
    

student_Data_Management_System/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        Student :
        {% block title %}
            Layout
        {% endblock title %}   
    </title>
     
    
    {% block link %}
        
    {% endblock link %}
        
    
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class='bg-slate-800'>
    <nav class="w-full bg-slate-700">
        <div class="flex items-center justify-between py-4 px-4 md:px-9">
          <!-- Logo and Navigation Links -->
          <div class="flex items-center">
            <ul class=" flex md:flex text-orange-600 items-center space-x-6 ml-4">
              <li><a href="{% url 'Show_data' %}" class="text-2xl md:text-4xl font-bold hover:text-orange-800">Data</a></li>
              <li><a href="{% url 'Show_data' %}" class="text-base md:text-xl font-medium hover:text-orange-800">View Data</a></li>
              <li><a href="{% url 'Add_data' %}" class="text-base md:text-xl font-medium hover:text-orange-800">Add Data</a></li>
            </ul>
          </div>
      
          <!-- Authentication Links -->
          <div>
            {% if user.is_authenticated %}
            <ul class="flex text-orange-600 items-center space-x-4">
              <li>
                <a href="{% url 'Logout' %}" class="inline-flex items-center justify-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-orange-500 hover:bg-orange-800 focus:outline-none focus:ring-2">
                  Logout
                </a>
              </li>
            </ul>
            {% else %}
            <ul class="flex text-orange-600 items-center space-x-4">
              <li>
                <a href="{% url 'Login' %}" class="inline-flex items-center justify-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-gray-500 hover:bg-gray-900 focus:outline-none focus:ring-2">
                  Login
                </a>
              </li>
              <li>
                <a href="{% url 'Register' %}" class="inline-flex items-center justify-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-orange-600 hover:bg-orange-700 focus:outline-none focus:ring-2">
                  Register
                </a>
              </li>
            </ul>
            {% endif %}
          </div>
        </div>
      
        <!-- Mobile Menu -->
        <div class="hidden md:hidden bg-slate-700">
          <ul class="flex flex-col text-orange-600 space-y-4 py-4 px-4">
            <li><a href="{% url 'Show_data' %}" class="text-xl font-bold hover:text-orange-800">Data</a></li>
            <li><a href="{% url 'Show_data' %}" class="text-base font-medium hover:text-orange-800">View Data</a></li>
            <li><a href="{% url 'Add_data' %}" class="text-base font-medium hover:text-orange-800">Add Data</a></li>
            {% if not user.is_authenticated %}
            <li><a href="{% url 'Login' %}" class="text-base font-medium hover:text-orange-800">Login</a></li>
            <li><a href="{% url 'Register' %}" class="text-base font-medium hover:text-orange-800">Register</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
      

    <div>
        {% block content %}
    <h1 class='text-center text-3xl font-bold p-5 text-orange-600'>Student Data Management System</h1>
    {% endblock content %} 
    </div> 
</body>
</html>